export const ADD_DOCKER_ITEM = 'ADD_DOCKER_ITEM';
export const DELETE_DOCKER_ITEM = 'DELETE_DOCKER_ITEM';
export const SET_LOADING_STATUS = 'SET_LOADING_STATUS';
export const SET_CREATION_LINK_STATUS = 'SET_CREATION_LINK_STATUS';
